-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               5.7.25 - MySQL Community Server (GPL)
-- Server OS:                    macos10.14
-- HeidiSQL Version:             10.1.0.5464
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for doctor_channeling
CREATE DATABASE IF NOT EXISTS `doctor_channeling` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `doctor_channeling`;

-- Dumping structure for table doctor_channeling.bookings
CREATE TABLE IF NOT EXISTS `bookings` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `fk_doctor` int(11) DEFAULT '0',
  `fk_session` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table doctor_channeling.bookings: ~0 rows (approximately)
/*!40000 ALTER TABLE `bookings` DISABLE KEYS */;
/*!40000 ALTER TABLE `bookings` ENABLE KEYS */;

-- Dumping structure for table doctor_channeling.customer
CREATE TABLE IF NOT EXISTS `customer` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `address` varchar(200) NOT NULL,
  `mobile` varchar(200) NOT NULL,
  `nic` varchar(50) NOT NULL,
  `email` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Dumping data for table doctor_channeling.customer: ~0 rows (approximately)
/*!40000 ALTER TABLE `customer` DISABLE KEYS */;
/*!40000 ALTER TABLE `customer` ENABLE KEYS */;

-- Dumping structure for table doctor_channeling.doctor
CREATE TABLE IF NOT EXISTS `doctor` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `qualification` varchar(100) DEFAULT NULL,
  `fk_doctor_category` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `doctor_caegory` (`fk_doctor_category`),
  CONSTRAINT `doctor_caegory` FOREIGN KEY (`fk_doctor_category`) REFERENCES `doctor_category` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- Dumping data for table doctor_channeling.doctor: ~2 rows (approximately)
/*!40000 ALTER TABLE `doctor` DISABLE KEYS */;
INSERT INTO `doctor` (`id`, `name`, `description`, `qualification`, `fk_doctor_category`) VALUES
	(1, 'Kavish Manjitha Perera', 'hfghfg', 'fghdgh', 134),
	(2, 'Thilina Kalum Moragoda', 'fgdhgh', 'fghdg', 120);
/*!40000 ALTER TABLE `doctor` ENABLE KEYS */;

-- Dumping structure for table doctor_channeling.doctor_category
CREATE TABLE IF NOT EXISTS `doctor_category` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(5000) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=504 DEFAULT CHARSET=latin1;

-- Dumping data for table doctor_channeling.doctor_category: ~385 rows (approximately)
/*!40000 ALTER TABLE `doctor_category` DISABLE KEYS */;
INSERT INTO `doctor_category` (`id`, `name`) VALUES
	(118, 'Any Specialization'),
	(119, 'Acupuncture'),
	(120, 'Allergy And Immunology'),
	(121, 'Allergy Specialist '),
	(122, 'Anaesthetist and Intensivist'),
	(123, 'Andrology And Male Fertility'),
	(124, 'Anesthetist Assistant'),
	(125, 'Applied Psychologist'),
	(126, 'Arthritis'),
	(127, 'udiologist'),
	(128, 'yurvedic And Alternative Medicine'),
	(129, 'yurvedic Cardiologist'),
	(130, 'yurvedic General Slimming &amp; Beauty'),
	(131, 'yurvedic Physician'),
	(132, 'yurvedic Physician (Boils &amp; Wounds Special)'),
	(133, 'yurvedic Skin Specialist'),
	(134, 'ack Pain Treatment '),
	(135, 'acteriologist'),
	(136, 'ehaviour Therapist'),
	(137, 'reast Feeding'),
	(138, 'reastfeeding and Counselling'),
	(139, 'anada Visa Medical'),
	(140, 'ancer Surgeon'),
	(141, 'ardiac Electrophysiologist'),
	(142, 'ardiographer'),
	(143, 'ardiologist '),
	(144, 'ardiologist And Cardiac Electrophysiologist'),
	(145, 'ardiologist Echo'),
	(146, 'ardiothoracic Surgeon'),
	(147, 'hemical Pathology'),
	(148, 'hest Physician'),
	(149, 'hest Specialist'),
	(150, 'hild and Adolescent Psychiatric'),
	(151, 'hild and Adolescent Psychologist'),
	(152, 'hild And Adolescent Psychology  Clinic'),
	(153, 'hild Psychiatrist'),
	(154, 'hild Psychologist'),
	(155, 'hildren Dentist'),
	(156, 'hildren s Respiratory Centre'),
	(157, 'hiropractor'),
	(158, 'linical  Geneticist'),
	(159, 'linical  Interventional Cardiologist'),
	(160, 'linical Audiologist'),
	(161, 'linical Embryologist'),
	(162, 'linical Haematologist'),
	(163, 'linical Health Psychologist'),
	(164, 'linical Hypnotist'),
	(165, 'linical Immunologist'),
	(166, 'linical Microbiologist'),
	(167, 'linical Neurologist'),
	(168, 'linical Neurophysiologist'),
	(169, 'linical Nutritionist'),
	(170, 'linical Oncologist'),
	(171, 'linical Physiologist'),
	(172, 'inical Psychologist'),
	(173, 'o-Ordinating Dr (Sleep Medicine)'),
	(174, 'olorectal Surgeon'),
	(175, 'ommunity Child Health( Development Assessment )'),
	(176, 'ommunity Medicine Physician'),
	(177, 'onsultant Cardiologist'),
	(178, 'onsultant Cardiothoracic Surgeon'),
	(179, 'onsultant Dental Surgeon'),
	(180, 'onsultant Dental Surgeon In Paediatric Dentistry'),
	(181, 'onsultant Dermatologist'),
	(182, 'onsultant In Fertility'),
	(183, 'onsultant In Reproductive Medicine'),
	(184, 'onsultant Judicial Medicine'),
	(185, 'onsultant Physician'),
	(186, 'osmetic Care Clinic And Cosmetic'),
	(187, 'osmetic Care Clinic And Cosmetic Physician'),
	(188, 'osmetic Center'),
	(189, 'osmetic Dermatology'),
	(190, 'osmetic Gynaecology'),
	(191, 'osmetic Oculoplasty'),
	(192, 'osmetologist'),
	(193, 'ounseling Psychologist'),
	(194, 'ounselling'),
	(195, 'ounselor'),
	(196, 'ounselor And Psychotherapist'),
	(197, 'ritical Care Medicine'),
	(198, 'ental And Maxillo -Facial Surgeon'),
	(199, 'ental Surgeon'),
	(200, 'ental Surgeon (Preventive Dentistry)'),
	(201, 'ental Surgeon / General And Laser'),
	(202, 'ental Surgeon In Prosthodontics And Endodontics'),
	(203, 'entist'),
	(204, 'ermatologist'),
	(205, 'ermatologist (Adult &amp; Paediatric)'),
	(206, 'iabetic Educator'),
	(207, 'iabetic Specialist'),
	(208, 'iabetologist'),
	(209, 'ietician'),
	(210, 'ietician AND/OR public health nutritionist'),
	(211, 'oppler Scan'),
	(212, 'ar; Nose and Throat Surgeon'),
	(213, 'CHO Scan'),
	(214, 'ducational Therapist'),
	(215, 'EG'),
	(216, 'lderly Care'),
	(217, 'Electroencephalography Specialist'),
	(218, 'Embryologist'),
	(219, 'EMDR Therapist'),
	(220, 'Endocrinologist'),
	(221, 'ENT - Head And Neck Surgeon'),
	(222, 'ENT Surgeon'),
	(223, 'Eye Diseases/Rheumatologist(Traditional Medicine)'),
	(224, 'Eye Surgeon'),
	(225, 'Family And General Counsellor'),
	(226, 'Family Physician'),
	(227, 'Family Planning /Reproductive And Female Sexual Health'),
	(228, 'Fertility Consultant'),
	(229, 'Fertility Counselor'),
	(230, 'Fertility Physician'),
	(231, 'Food &amp; Nutrition'),
	(232, 'Gastroenterological Surgeon'),
	(233, 'Gastroenterologist'),
	(234, 'Gastrointestinal Surgeon'),
	(235, 'General'),
	(236, 'o-Ordinating Dr (Sleep Medicine)'),
	(237, 'olorectal Surgeon'),
	(238, 'ommunity Child Health( Development Assessment )'),
	(239, 'ommunity Medicine Physician'),
	(240, 'onsultant Cardiologist'),
	(241, 'onsultant Cardiothoracic Surgeon'),
	(242, 'onsultant Dental Surgeon'),
	(243, 'onsultant Dental Surgeon In Paediatric Dentistry'),
	(244, 'onsultant Dermatologist'),
	(245, 'onsultant In Fertility'),
	(246, 'onsultant In Reproductive Medicine'),
	(247, 'onsultant Judicial Medicine'),
	(248, 'onsultant Physician'),
	(249, 'osmetic Care Clinic And Cosmetic'),
	(250, 'osmetic Care Clinic And Cosmetic Physician'),
	(251, 'osmetic Center'),
	(252, 'osmetic Dermatology'),
	(253, 'osmetic Gynaecology'),
	(254, 'osmetic Oculoplasty'),
	(255, 'osmetologist'),
	(256, 'ounseling Psychologist'),
	(257, 'ounselling'),
	(258, 'ounselor'),
	(259, 'ounselor And Psychotherapist'),
	(260, 'ritical Care Medicine'),
	(261, 'ental And Maxillo -Facial Surgeon'),
	(262, 'ental Surgeon'),
	(263, 'ental Surgeon (Preventive Dentistry)'),
	(264, 'ental Surgeon / General And Laser'),
	(265, 'ental Surgeon In Prosthodontics And Endodontics'),
	(266, 'entist'),
	(267, 'ermatologist'),
	(268, 'ermatologist (Adult &amp; Paediatric)'),
	(269, 'iabetic Educator'),
	(270, 'iabetic Specialist'),
	(271, 'iabetologist'),
	(272, 'ietician'),
	(273, 'ietician AND/OR public health nutritionist'),
	(274, 'oppler Scan'),
	(275, 'ar; Nose and Throat Surgeon'),
	(276, 'CHO Scan'),
	(277, 'ducational Therapist'),
	(278, 'EG'),
	(279, 'lderly Care'),
	(280, 'Electroencephalography Specialist'),
	(281, 'Embryologist'),
	(282, 'EMDR Therapist'),
	(283, 'Endocrinologist'),
	(284, 'ENT - Head And Neck Surgeon'),
	(285, 'ENT Surgeon'),
	(286, 'Eye Diseases/Rheumatologist(Traditional Medicine)'),
	(287, 'Eye Surgeon'),
	(288, 'Family And General Counsellor'),
	(289, 'Family Physician'),
	(290, 'Family Planning /Reproductive And Female Sexual Health'),
	(291, 'Fertility Consultant'),
	(292, 'Fertility Counselor'),
	(293, 'Fertility Physician'),
	(294, 'Food &amp; Nutrition'),
	(295, 'Gastroenterological Surgeon'),
	(296, 'Gastroenterologist'),
	(297, 'Gastrointestinal Surgeon'),
	(298, 'eneral and Laparoscopic Surgeon'),
	(299, 'General Physician'),
	(300, 'General Practitioner'),
	(301, 'General Surgeon'),
	(302, 'Genereal and Interventional Cardiologist'),
	(303, 'Genetic Counselor'),
	(304, 'Geneticist'),
	(305, 'Genito Urinary Surgeon'),
	(306, 'Geriatric Physician'),
	(307, 'Geriatrician/ Elderly Care Specialist'),
	(308, 'Gynae Oncology'),
	(309, 'Gynaecological Cancer Surgeon'),
	(310, 'Gynaecological Oncologist'),
	(311, 'Gynaecological Oncosurgeon'),
	(312, 'Gynaecologist'),
	(313, 'Gynaecologist (VOG)'),
	(314, 'Gynecologist and Consultant in Fertility'),
	(315, 'Haemato-oncologist'),
	(316, 'Haematologist'),
	(317, 'Hair Clinic'),
	(318, 'Hair Transplant'),
	(319, 'Health Management'),
	(320, 'Hepatobiliary Liver Transplant Surgeon'),
	(321, 'Hepatobiliary Surgeon'),
	(322, 'Hepatologist '),
	(323, 'Hernia Centre'),
	(324, 'Histopathologist'),
	(325, 'HOLTER MONITORING'),
	(326, 'Homeopathy'),
	(327, 'Human Nutritionist'),
	(328, 'Imago Therapist'),
	(329, 'Immunologist'),
	(330, 'Implantologist'),
	(331, 'Internal Medicine'),
	(332, 'Interventional Radiologist'),
	(333, 'Kidney Dialysis'),
	(334, 'Kidney Transplant Surgeon '),
	(335, 'Lactation Counseling'),
	(336, 'Laparoscopic and Bariatric Surgeon'),
	(337, 'Laparoscopy And Colorectal Surgeon'),
	(338, 'Lifestyle Therapist'),
	(339, 'Liver Centre'),
	(340, 'Low Vision Practitioner'),
	(341, 'Manual Therapist'),
	(342, 'Maxillofacial Surgeon'),
	(343, 'Medical And Clinical Geneticist'),
	(344, 'Medical Examination (Visa)'),
	(345, 'Medical Fitness Certificate for Sports '),
	(346, 'Medical Gastroenterologist'),
	(347, 'Medical Microbiologist'),
	(348, 'Medical Nutritionist'),
	(349, 'Medical Officer'),
	(350, 'Medical Officer - Ophthalmology'),
	(351, 'Medical Virologist'),
	(352, 'Memory Clinic'),
	(353, 'Mens Sexual And Reproductive Health'),
	(354, 'Menstrual Disorder Clinic'),
	(355, 'Microbiologist  '),
	(356, 'Mycologist'),
	(357, 'Neonatal Paediatrician'),
	(358, 'Neonatologist'),
	(359, 'Nephrologist'),
	(360, 'Neuro Physician'),
	(361, 'Neuro Physiologist'),
	(362, 'Neuro Surgeon'),
	(363, 'Neurologist'),
	(364, 'New Zealand Visa Medical'),
	(365, 'Nutrition Physician'),
	(366, 'Nutrition Specialist'),
	(367, 'Nutritionist'),
	(368, 'Nutritious Advice'),
	(369, 'Obstetrician'),
	(370, 'Obstetrician &amp; Gynaecologist'),
	(371, 'Obstetrician And Fetal Medicine Specialist'),
	(372, 'Obstetrician; Fetal Medicine Specialist &amp; Genetic Consultation'),
	(373, 'Occupational Medicine'),
	(374, 'Occupational Physician'),
	(375, 'Occupational Therapist'),
	(376, 'Oculoplastic Surgeon'),
	(377, 'OMF Surgeon &amp; Specialist in Oral Medicine'),
	(378, 'Oncological Surgeon'),
	(379, 'Oncologist'),
	(380, 'Oncologist - Cancer Specialist'),
	(381, 'Ophthalmologist'),
	(382, 'Optometrist'),
	(383, 'Oral And Maxillofacial Surgeon'),
	(384, 'Oral Dental And Maxillofacial Surgeon'),
	(385, 'Oral surgeon'),
	(386, 'Orthodontic Surgeon'),
	(387, 'Orthodontist'),
	(388, 'Orthopaedic Surgeon'),
	(389, 'Orthopaedic Surgeon (Adult &amp; Paediatric)'),
	(390, 'Orthopedics (Traditional Medicine)'),
	(391, 'Paediatric Cardiac Surgeon'),
	(392, 'Paediatric Cardiologist	'),
	(393, 'Paediatric Cardiothoracic Surgeon'),
	(394, 'Paediatric Chest Physician'),
	(395, 'Paediatric Dermatologist'),
	(396, 'Paediatric Endocrinologist'),
	(397, 'Paediatric Eye Surgeon'),
	(398, 'Paediatric Intensivist'),
	(399, 'Paediatric Interventional Cardiologist'),
	(400, 'Paediatric Neonatologist'),
	(402, 'aediatric Neurologist'),
	(403, 'Paediatric Oncologist'),
	(404, 'Paediatric Oncologist(Child And Adolescents)'),
	(405, 'Paediatric Optometrist'),
	(406, 'Paediatric Orthopaedic Surgeon'),
	(407, 'Paediatric Physiotherapist'),
	(408, 'Paediatric Psychiatrist'),
	(409, 'Paediatric Pulmonologist'),
	(410, 'Paediatric Surgeon	'),
	(411, 'Paediatric Vaccinologist'),
	(412, 'Paediatrician'),
	(413, 'Paediatrician And Neonatologist'),
	(414, 'Paediatrics And Paediatric Neurodisability'),
	(415, 'Pain Management'),
	(416, 'Panchakarma'),
	(417, 'Parasitologist'),
	(418, 'Pathologist'),
	(419, 'Periodontist'),
	(420, 'Physician'),
	(421, 'Physician And Endocrinologists'),
	(422, 'Physician/Chest Physician(Traditional Medicine)'),
	(423, 'Physiologist'),
	(424, 'Physiotherapist'),
	(425, 'Physiotherapy/Pain And Orthopedic Neuro Rehabilitation'),
	(426, 'Plastic And Reconstructive Surgeon'),
	(427, 'Plastic Surgeon'),
	(428, 'pre participation evaluation'),
	(429, 'Prosthetist And Orthoptist'),
	(430, 'Prosthodontist'),
	(431, 'Psychiatrist'),
	(432, 'Psychiatrist (Child And Adolescents)'),
	(433, 'Psycho Social Practitioner'),
	(434, 'Psychological Counselling'),
	(435, 'Psychologist	'),
	(436, 'Public Health Nutritionist'),
	(437, 'Pulmonary Rehabilitation Therapist'),
	(438, 'Pulmonologist'),
	(439, 'Quarterisation Charges'),
	(440, 'Radiologist'),
	(441, 'Reproductive Endocrinologist'),
	(442, 'Respiratory Medicine'),
	(443, 'Respiratory Physician'),
	(444, 'Restorative Dentist'),
	(445, 'Rheumatologist'),
	(446, 'Rheumatology And  Rehabilitation'),
	(447, 'S.T.D'),
	(448, 'Scanning'),
	(449, 'Senior Orthoptist'),
	(450, 'Sexual Health'),
	(451, 'Sexual Medicine'),
	(452, 'Sexual Wellness'),
	(453, 'Skin Care And Cosmetic Centre - Plastic Surgeon'),
	(454, 'Skin Care And Cosmetic Consultant Dermatologist'),
	(455, 'Skin Care And Cosmetic Oculoplastic Surgeon'),
	(456, 'Sleep Health and Community Physician'),
	(457, 'Special Education Consultant'),
	(458, 'Special Educational Needs'),
	(459, 'Specialist in Laparoscopic Surgery'),
	(460, 'Specialized Child Psychology Clinic'),
	(461, 'Speech  and Language Pathologist and Audiologist'),
	(462, 'Speech And Language Therapist'),
	(463, 'Speech Language Pathologist'),
	(464, 'Speech Pathologist'),
	(465, 'Speech Pathologist/Therapist'),
	(466, 'Speech Therapist'),
	(467, 'Speech Therapist/Autism'),
	(468, 'SPORT INJURY CLINIC'),
	(469, 'Sports and Exercise Medicine'),
	(470, 'Sports And Exercise Physician'),
	(471, 'Sports Medicine'),
	(472, 'Sports Medicine Low Back Pain Management'),
	(473, 'Sports Nutrition &amp; Performance'),
	(474, 'Sports Physiotherapy/Pain Management'),
	(475, 'Sports Psychology'),
	(476, 'Study Disorders And Counselling'),
	(477, 'Sub Fertility Specialist'),
	(478, 'Subspecialist in Reproductive Medicine'),
	(479, 'Surgeon'),
	(480, 'Telemedicine'),
	(481, 'Therapist for drug and alcohol addiction'),
	(482, 'Thoracic Surgeon'),
	(483, 'Transfusion Medicine'),
	(484, 'Transfusion Physician'),
	(485, 'Transplant Surgeon'),
	(486, 'Trauma Counselor'),
	(487, 'Trauma Surgeon'),
	(488, 'Ultra Sound Scan'),
	(489, 'Urological Surgeon'),
	(490, 'Urologist'),
	(491, 'UV Therapy'),
	(492, 'Vaccine Advice'),
	(493, 'Vaccinologist'),
	(494, 'Vascular And Transplant Surgeon'),
	(495, 'Vascular And Transplant Surgeon Liver And Kidney'),
	(496, 'Vascular Surgeon'),
	(497, 'Venereologist (S.T.D)'),
	(498, 'Virologist'),
	(499, 'Vitreoretinal Surgeon '),
	(500, 'VOG Scan'),
	(501, 'Weight Management'),
	(502, 'Well Woman Clinics'),
	(503, 'Wound Consultation');
/*!40000 ALTER TABLE `doctor_category` ENABLE KEYS */;

-- Dumping structure for table doctor_channeling.doctor_session
CREATE TABLE IF NOT EXISTS `doctor_session` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `start_time` time NOT NULL,
  `end_time` time NOT NULL,
  `max_epointments` int(11) NOT NULL DEFAULT '0',
  `availaility` tinyint(4) NOT NULL DEFAULT '0',
  `fk_doctor` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_doctor` (`fk_doctor`),
  CONSTRAINT `fk_doctor` FOREIGN KEY (`fk_doctor`) REFERENCES `doctor` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

-- Dumping data for table doctor_channeling.doctor_session: ~3 rows (approximately)
/*!40000 ALTER TABLE `doctor_session` DISABLE KEYS */;
INSERT INTO `doctor_session` (`id`, `date`, `start_time`, `end_time`, `max_epointments`, `availaility`, `fk_doctor`) VALUES
	(1, '2019-06-23', '23:17:08', '23:17:09', 5, 0, 1),
	(2, '2019-06-24', '23:17:08', '23:17:09', 5, 0, 1),
	(3, '2019-06-25', '23:17:08', '23:17:09', 5, 0, 2),
	(4, '2019-06-26', '23:17:08', '23:17:09', 5, 0, 2),
	(5, '2019-06-27', '23:17:08', '23:17:09', 5, 0, 2);
/*!40000 ALTER TABLE `doctor_session` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
